### ISSUE TITLE
Dicionário de dados

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/lung-cancer#3]
A equipe deve criar um arquivo (ou vários) de dicionário de dados, contendo informações referentes aos conjuntos de dados utilizados no projeto.

 - [ ] Criar arquivo `data/external/dicionario.csv` contendo as seguintes colunas: `variavel`, `significado`, `tipo`.
 - [ ] Inserir informações referentes ao arquivo de dados utilizado no projeto.

**Comment by Luizrev** [comment]
inici
