### ISSUE TITLE
Exploração de dados

### ISSUE THREAD

**Issue by omadson** [atlantico-academy/lung-cancer#4]
A equipe deve criar um notebook de análise exploratória `notebooks/01-exploratory_data_analysis.ipynb`, contendo as seguintes seções de texto:

  - [x] **Descrição dos dados**: informações sobre a quantidade de instâncias, variáveis e seus tipos, quantidade de valores faltantes. Utilize o dicionário de dados nessa seção.
  - [x]  **Perguntas de partida e hipóteses**: que tipo de informações podem ser obtidas a partir dos dados e quais hipóteses podem ser levantadas?
  - [x]  **Insights**: respostas às perguntas feitas na seção anterior e quais informações interessantes podem ser levantadas através dos dados?

**Comment by rafaelsilva81** [comment]
Iniciando tarefa
